### ISSUE TITLE
ModuleNotFoundError: No module named 'wget'

### ISSUE THREAD

**Issue by kshru9** [Adi-iitd/AI-Art#7]
I tried executing CycleGAN version for the style transfer using `! python CycleGAN-PL.py` in gcolab.

But its showing following error

Traceback (most recent call last):
  File "CycleGAN-PL.py", line 2, in <module>
    from Imports import *
  File "/content/drive/Shareddrives/ML/AI-Art/src/CycleGAN/Imports.py", line 3, in <module>
    import os, wget, zipfile, shutil
ModuleNotFoundError: No module named 'wget'

**Comment by kshru9** [comment]
> I tried executing CycleGAN version for the style transfer using `! python CycleGAN-PL.py` in gcolab.
> 
> But its showing following error
> 
> Traceback (most recent call last):
> File "CycleGAN-PL.py", line 2, in
> from Imports import *
> File "/content/drive/Shareddrives/ML/AI-Art/src/CycleGAN/Imports.py", line 3, in
> import os, wget, zipfile, shutil
> ModuleNotFoundError: No module named 'wget'

Its solved using `! pip install wget`
